Car tesla = new Car(); 
tesla.carColor = 'black';
tesla.carName = 'Model S';
tesla.driveAtMaxSpeed();
tesla.drive();
tesla.switchOn();
// system.debug('tesla ->' +tesla);

Car bmw = new Car();
bmw.carColor = 'white';
bmw.carName= 'X7';
bmw.driveAtMaxSpeed();

bmw.drive();
bmw.switchOn();


 //system.debug('bmw-> '+ bmw);

Car toyota = new Car();
toyota.drive();
// valid where it is declared 
// no strict equal? 

