public  class GeneralClass {

    public void createStudent(){
        Student5 s1 = new Student5();
        s1.Name = ' Melda';
        s1.BirthDate = date.newInstance(1990, 06, 28);
        s1.SchoolName = 'Oxford';
        system.debug(s1);

        Student5 s2 = new Student5();
        s2.Name = ' Menar';
        s2.BirthDate = date.newInstance(1993, 07, 28);
        s2.SchoolName = 'Harward';
        system.debug(s2);
    }
    public void metot2(){
        integer i = 5+5+5+5;
        System.debug(i);

    }
}
