public class Ogrenci {
    public Ogrenci() {
        system.debug('Yeni bir kayit yapildi');//cagirmasakta bu mesaji verecek her kayit 
    }
//constructer classin icinde tanimliyoruz. 
    public string firstName;
    public string lastName; 
    private string schoolName = 'Dream school';
    public string className;
    public string language;
    public Boolean art;
    public Boolean sport;
    public integer ingGrade;
    public integer mathGrade;
    public integer science;
}

