public   class Practice11 {

    public static List<ogrenci11> ogrenciList= new List<string>(); 
    // bos liste olustur 
    public static void ogrenciler() {

            Ogrenci11 s1 = new Ogrenci11('Lisa', 'Jon', 87);
            ogrenciList.add(s1);

            Ogrenci11 s2 = new Ogrenci11('Rabia', 'Oz', 100);
            ogrenciList.add(s2);

            Ogrenci11 s3 = new Ogrenci11('Sarah', 'Oz', 100);
            ogrenciList.add(s3);

        
    }
}
