// Selamlama s = new Selamlama();
// s.selam('Hintce');
// s.selam('Ingilizce');
// s.selam('rusca');
// s.selam('turkce');
// s.selam('arapca');
// s.selam('Hintce');

Selamlama s2 = new Selamlama();
system.debug(s2.selam2('hintce'));
system.debug(s2.selam2('ingilizce'));
system.debug(s2.selam2('rusca'));


string isim = '  ';
for(integer i = 1; i<= 5 ; i++) {
   isim+= 'rabia ';
   System.debug(isim);
}

