public  class ListCollection11 {
public static void printListEachItem(List<string> adList) {
    integer counter = 1;

    for(string eachItem : adList) {
        system.debug('for' + counter+ '  defa dondu');
        system.debug(eachItem);
        counter++;
    }
}
public static decimal  listEachItemSum(List<decimal> adList) {
    List<decimal> numbers = new List<decimal> {3.14, 2.16, 5.75, 7.01};
    for (decimal i : numbers) {
      System.debug(i);
    }

 
}
}
  
