public  class MathPractice {

    // public decimal practiceOne(decimal l, decimal w) {
    //     decimal perimeter = 2*(l+w);
    //     system.debug('The perimeter of the  rectangle is: ' +perimeter);
    //     return perimeter;
    // }

    public decimal practice2(decimal boy, decimal kilo){
        decimal VKI = (kilo/boy*boy).setScale(3);
        system.debug(' VKI olcusu: ' + VKI);
        return VKI;

    }

    public decimal practice3(decimal l, decimal w, decimal area){
        decimal area = 0;
        switch on islem {
            when 'area' {
                
            }
        }
   
        

    }
}
